server:
  port: 8081
spring:
  profiles:
    include: dao
  datasource:
    username: root
    password: tj2914**
    url: jdbc:mysql://localhost:3306/sven?characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379
